services:
  web:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
