name: CI

on:
  push:
    branches: [ main, feat/**, fix/** ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Typecheck
        run: pnpm -s tsc -p tsconfig.json --noEmit

      - name: Unit tests
        run: pnpm test    # Vitest: kein --ci Flag

      - name: Build
        run: pnpm build
